src/Entity/Tweet.php
<?php

namespace App\Entity;

use App\Repository\TweetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=TweetRepository::class)
 */
class Tweet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=144)
     */
    private $text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
<<<<<<< HEAD
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="tweets", cascade={"remove"})
     * @ORM\JoinColumn(name="users_id", onDelete="CASCADE")
=======
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="tweets")
     * @ORM\JoinColumn(name="id", referencedColumnName="id")
>>>>>>> 84ac1062a1cd2df3559233c5be6e87b7b8b4fb60
     */
    private $users;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_like;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="tweet")
     */
    private $likes;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getNombreLike(): ?int
    {
        return $this->nombre_like;
    }

    public function setNombreLike(int $nombre_like): self
    {
        $this->nombre_like = $nombre_like;

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setTweet($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getTweet() === $this) {
                $like->setTweet(null);
            }
        }

        return $this;
    }
}

templates/_partials/feed.html.twig
<section class="feed">
    <div class="title">
        <h1>Accueil</h1>
    </div>
    <div class="whats_up">
        <div class="icon">
            <img src="{{ asset('img/icon/twitter_white.png') }}" class="img-fluid">
        </div>
        <div class="tweet_form">


            {{ form_start(form, {'attr': {'id': 'formID'}}) }}
            {{ form_row(form.text) }}
            <div class="form_row d-flex">
                <div class="file_wrapper">
                    <i class="fa fa-image"></i>
                    {{ form_row(form.image) }}
                </div>
                <div class="button" style="margin-left: auto">
                    {{ form_row(form.submit) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="intersection"></div>
    <div class="news_feed">
        {% for tweet in tweets%}
        <div class="tweet">
            <input type="hidden" id="idtweet" value="{{ tweet.id }}">
            <a class="absolute_link" href="#"></a>
            <div class="icon">
                <img src="{{ asset('img/icon/twitter_white.png') }}" class="img-fluid">
            </div>
            <div class="content">
                <div class="author">
                    <h3 class="pseudo">Pseudonyme {{ user }} <strong>@Nom_du_compte</strong></h3>
                    <p class="mx-1">·</p>
                    <p>14/03/2021</p>
                </div>
                <div class="text  w-100">
                    <p class="text-justify">{{ tweet.text }}</p>
                </div>
                {% if tweet.image != null %}
                    <div class="img">
                        <img src="{{ asset('image_tweet/'~tweet.image) }}">
                    </div>
                {% endif %}
                <div class="interacting">
                    <div class="item">
                        <p><i class="fa fa-comment"></i>3</p>
                    </div>
                    <div class="item like">
                        <p><a id="like{{ tweet.id }}" onclick="like({{ tweet.id }})"><i class="fa fa-heart"></i></a>{{ tweet.nombreLike}}</p>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</section>

templates/_partials/slider_bar.html.twig
<section class="slide_bar">
    <div class="menu">
        <img src="{{ asset('img/icon/twitter_white.png') }}">
        <div class="list_link">
            <div class="item">
                <a class="absolute_link" href="{{ path('user_dashboard') }}"></a>
                <i class="fa fa-home"></i>
                <p>Accueil</p>
            </div>
            <div class="item">
                <a class="absolute_link" href="{{ path('user_profil') }}"></a>
                <i class="fa fa-user"></i>
                <p>Profil</p>
            </div>
        </div>
        <div class="profil">
            <div class="icon">
                <img src="{{ asset('img/icon/twitter_white.png') }}" class="img-fluid">
            </div>
            <div class="name">
                <h3>Pseudonyme</h3>
                <h5>@Nom_du_compte</h5>
            </div>
        </div>
    </div>
</section>

templates/_partials/tweet_comments.html.twig
<section class="feed">
    <div class="title">
        <h1>Tweeter</h1>
    </div>
    <div class="comment">
        <div class="tweet">
            <div class="icon">
                <img src="{{ asset('img/icon/twitter_white.png') }}" class="img-fluid">
            </div>
            <div class="content">
                <div class="author">
                    <h3 class="pseudo">Pseudonyme <br><strong>@Nom_du_compte</strong></h3>
                </div>
                <div class="text">
                    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean scelerisque
                        ultricies lorem,
                        eget congue nisi egestas ut. Duis blandit orci ac augue viverra, id gravida odio mattis.
                        Aenean ut metus consectetur ipsum viverra finibus vitae quis diam.</p>
                </div>
                <div class="date">
                    <p>15 avr. 2021</p>
                </div>
                <div class="interacting">
                    <div class="item">
                        <p><i class="fa fa-comment"></i>3</p>
                    </div>
                    <div class="item">
                        <p><i class="fa fa-heart"></i>18</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="news_feed">
            <div class="tweet">
                <a class="absolute_link" href="#"></a>
                <div class="icon">
                    <img src="{{ asset('img/icon/twitter_white.png') }}" class="img-fluid">
                </div>
                <div class="content">
                    <div class="author">
                        <h3 class="pseudo">Pseudonyme <strong>@Nom_du_compte</strong></h3>
                        <p class="mx-1">·</p>
                        <p>14/03/2021</p>
                    </div>
                    <div class="text">
                        <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                            scelerisque ultricies lorem.</p>
                    </div>
                    <div class="interacting">
                        <div class="item">
                            <p><i class="fa fa-comment"></i>0</p>
                        </div>
                        <div class="item">
                            <p><i class="fa fa-heart"></i>12</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>